spring:
  jpa:
    hibernate:
      format_sql: true
      use_sql_comments: true
      ddl-auto: create
    show-sql: true
    database: postgresql
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:postgresql://database-1.ceftnxqn28g8.ap-northeast-2.rds.amazonaws.com/postgres
    username: postgres
    password: postgres2023!
    driver-class-name: org.postgresql.Driver
#  h2:
#    console:
#      enabled: true
  defer-datasource-initialization: true


  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: 41e262d361b68b616775006c09b25c48
            client-secret: ikY0o83vmzLcDtP0GbsM3idXuAfHjoeq
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#            redirect-uri: https://d1zdvff23sqy4w.cloudfront.net/mySchedule
#            redirect-uri: http://ec2-43-200-157-69.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/kakao
#            redirect-uri: https://d1zdvff23sqy4w.cloudfront.net/mySchedule
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
  jwt:
    secret:
      key: ENC(wo85QhTHIrilTgPhSHmBKg==)